Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "file", source: "Miniconda3-latest-Linux-x86_64.sh", destination: "/home/vagrant/miniconda.sh"
  # We can get unixodbc from apt or conda.
  # config.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get install -y unixodbc unixodbc-dev"
  config.vm.provision "shell", path: "install-miniconda.sh"
end
