Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "file", source: "Miniconda3-latest-Linux-x86_64.sh", destination: "/home/vagrant/miniconda.sh"
  config.vm.provision "shell", path: "install-miniconda.sh"
end
